
# This file is used to configure your Supabase project.
# It defines the settings that apply to different Supabase resources.

project_id = "fvegutbytclvrdcfxdyr"

[api]

[db]

# Enable Supabase Realtime for the feedback table
[realtime]
enabled = true
database_polling_interval_milliseconds = 1000
max_subscription_slots = 100
subscription_events = "insert, update, delete"

[[realtime.tables]]
name = "feedback"
schema = "public"
events = ["INSERT", "UPDATE", "DELETE"]

[auth]
# Configure auth settings (advanced)
# site_url = "https://example.com"
# additional_redirect_urls = ["https://example.com/callback"]

[analytics]
# Configure analytics settings (advanced)
