// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvegutbytclvrdcfxdyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2ZWd1dGJ5dGNsdnJkY2Z4ZHlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNjg1NzQsImV4cCI6MjA1OTc0NDU3NH0.QrS-sHCyQOgQrNsKUU5BAsNh7Q8SoRKfKFEVAN-WWQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);